Next prev buttons components
WeFriiends/wf-mobile-backup pull request #1
Opened 2023-12-11 00:30 UTC by LenaYork

add next button component
add previous button component 
![image](https://github.com/WeFriiends/wf-mobile-backup/assets/20025262/0c9ba921-3394-45b0-9de8-500147c8cb31)

2023-12-11 03:19 UTC, NataliaDoudkina requested changes
Left a few comments

2023-12-11 03:19 UTC, NataliaDoudkina commented on apps/expo/App.tsx
> +
Remove empty line

2023-12-11 03:19 UTC, NataliaDoudkina commented on apps/expo/%ProgramData%/Microsoft/Windows/UUS/State/_active.uusver
> +1212.2309.20012.0
what is this for?

2023-12-11 03:19 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
>  const NextStepButton = () => {
I am getting an error "fontFamily "Inter" is not a system font and has not been loaded through Font.loadAsync." in the terminal when the component is loaded

2023-12-11 03:19 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
> +      style={[styles.button, { backgroundColor: isPressed ? '#F05A22' : '#FB8F67' }]}
I think the background color of this button depends on whether input field is validated or not according to Figma. It should have no color if the input field is empty/failed validation, and only after validation passes it should change bg color to that orange one.
We are using typescript, so you should add types everywhere
These two button components will actually have a few prop passed to it -  you can see the function in the original Next button in AddName component. The color of the button is determined by TextInput Attribute onChangeText -  should be passed to the NextStepButton component as well.

2024-01-24 04:10 UTC, NataliaDoudkina requested changes

2024-01-24 04:10 UTC, NataliaDoudkina commented on apps/expo/App.tsx
> +        <NextStepButton />
We don't need buttons here. They should be placed into an appropriate folder and used as needed in any component.

2024-01-24 04:10 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
> +      style={[styles.button, { backgroundColor: isPressed ? '#F05A22' : '#FB8F67' }]}
I don't think this comment was addressed.

2024-02-06 17:51 UTC, LenaYork commented on packages/app/components/ui/NextStepButton.tsx
> +      style={[styles.button, { backgroundColor: isPressed ? '#F05A22' : '#FB8F67' }]}
It was. They all have been but since I'm still getting the font issue there haven't been any updates to the PR

2024-02-16 21:38 UTC, closed without merging