Add next page and previous page button components
WeFriiends/wf-mobile-backup pull request #4
Opened 2024-02-16 21:38 UTC by LenaYork

add next button component
add previous button component
![image](https://github.com/WeFriiends/wf-mobile-backup/assets/20025262/ce517bf9-0a67-4f4e-826c-dbef98dbc008)

clickup task : https://app.clickup.com/t/8692uawem

2024-02-19 15:40 UTC, LyubovSugak commented on packages/app/components/ui/NextStepButton.tsx
> +const NextStepButton = (props: NextStepButtonProps) => {
Define explicitly props, plz

2024-02-19 15:41 UTC, LyubovSugak commented on packages/app/components/ui/NextStepButton.tsx
> +      activeOpacity={1}
also should be optional

2024-02-19 15:44 UTC, LyubovSugak requested changes
ask Olga designer - as far as i remember should be used svg only, and move plz to separate public folder

2024-02-19 15:44 UTC, LyubovSugak commented on packages/app/components/ui/PreviousStepButton.tsx
> +const PreviousStepButton = (props: PreviousStepButtonProps) => {
same here regards of props

2024-02-19 15:46 UTC, LyubovSugak commented on packages/app/components/ui/PreviousStepButton.tsx
> +      style={[styles.circle, { backgroundColor: isPressed ? '#FB8F67' : '#FEDED2' }]}
regards of style - pass it as a prop, it gives more options in the future and less rework

2024-02-19 20:24 UTC, NataliaDoudkina requested changes

2024-02-19 20:24 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
> +const NextStepButton = (props: NextStepButtonProps) => {
agree. The idea is to have less details in the generic components  -  then you can easily manipulate and change them later. Even 'Next'  could be passed as  a prop if in the future we will want to use this button component for some other buttons -  but that's not necessary here  -  it's just as an example

2024-02-19 21:46 UTC, NataliaDoudkina requested changes

2024-02-19 21:46 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
> +  handleInput: () => void;
This function takes action: string as a parameter

2024-02-19 21:46 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
> +      onPress={handleInput}
handleInput is a prop function, you will need to define a handler for it in this component -  and actually here it gets a bit complicated since the main function exists in the parent component  -  Profile.js, then it passes a prop to the page component and from there it will be passed to the button component

2024-02-19 21:59 UTC, NataliaDoudkina requested changes

2024-02-19 21:59 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
> +import React, { useState } from 'react';
useState is not used , remove

2024-02-19 22:39 UTC, NataliaDoudkina reviewed
I don't think this code will work because the props are related to each other on two levels and right now what it does  -  it changes the color of the Next button and does not take a user to the next page.
The handleInput function takes an action as a parameter and this allows to render next component. 
 The state in those profile components depends on Profile.js and a component itself and you will need to add handlers to the button component to be able to pass props to the profile page and then from the profile page to the main Profile component. I advise you write a diagram on how it' supposed to work in terms of passing state logic. What you can do is to pass the action from the button component to the profile page component (e.g. addName) and then AddName will deal with it by passing it up to the Profile.js . Please test your code by adding the button component to the profile page component  and see if you get the desired result. I will update profile page components to remove api calls from them

2024-03-11 15:03 UTC, LenaYork commented on packages/app/components/ui/NextStepButton.tsx
> +import React, { useState } from 'react';
- [x] removed

2024-03-11 15:04 UTC, LenaYork commented on packages/app/components/ui/NextStepButton.tsx
> +      onPress={handleInput}
- [x] defined a handler

2024-03-11 15:04 UTC, LenaYork commented on packages/app/components/ui/NextStepButton.tsx
> +  handleInput: () => void;
- [x] added action as a parameter

2024-03-11 15:07 UTC, LenaYork commented on packages/app/components/ui/NextStepButton.tsx
> +      activeOpacity={1}
- [x] activeOpacity is optional and comes as a prop now

2024-03-11 15:10 UTC, LenaYork commented
> ask Olga designer - as far as i remember should be used svg only, and move plz to separate public folder

- [x] replaced png with svg

2024-03-16 01:47 UTC, NataliaDoudkina reviewed
left some comments, i did not comment on style props -  i think Lyuba can take a better look

2024-03-16 01:47 UTC, NataliaDoudkina commented on packages/app/components/profileBuilder/AddName.tsx
> +import PreviousStepButton from '../ui/PreviousStepButton'
button is not used on this page, remove import

2024-03-16 01:47 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
> +  const buttonHandler = () => {
i would call it onPressHandler , we should develop naming convention for the mobile app and use that

2024-03-16 01:47 UTC, NataliaDoudkina commented on packages/app/components/profileBuilder/AddName.tsx
> +            caption="next"
should be capital N

2024-03-16 01:47 UTC, NataliaDoudkina commented on packages/app/components/ui/NextStepButton.tsx
> +      alignItems: any;
normally should avoid using any type in Typescript

2024-03-16 01:47 UTC, NataliaDoudkina commented on packages/app/components/ui/PreviousStepButton.tsx
> +// const styles = StyleSheet.create({
why do we need to keep commented out code?

2024-03-20 15:09 UTC, LyubovSugak requested changes

2024-03-20 15:09 UTC, LyubovSugak commented on yarn.lock
why lock file is changed?

2024-03-20 15:09 UTC, LyubovSugak commented on packages/app/components/ui/NextStepButton.tsx
> +  styles: {
you don't need type style, check out how to assign, i suppose it can be Record {<string, string>}

2024-04-02 19:07 UTC, LyubovSugak commented on packages/app/lib/assets/BackArrowSVG.js
why does it live here?

2024-04-04 14:04 UTC, LenaYork commented on packages/app/components/profileBuilder/AddName.tsx
> +import PreviousStepButton from '../ui/PreviousStepButton'
- [x] removed button import

2024-04-04 14:07 UTC, LenaYork commented on packages/app/components/profileBuilder/AddName.tsx
> +            caption="next"
it was discussed during a weekly zoom call that it shouldn't be a capital letter since the font is different from the desktop one. Should I still bring back the capital letter or should I leave the current one?

2024-04-04 14:08 UTC, LenaYork commented on packages/app/components/ui/NextStepButton.tsx
> +  const buttonHandler = () => {
- [x] changed handler name into onPressHandler

2024-04-04 14:08 UTC, LenaYork commented on packages/app/components/ui/NextStepButton.tsx
> +      alignItems: any;
- [x]  removed type 'any' with the string one

2024-04-04 14:10 UTC, LenaYork commented on packages/app/components/ui/PreviousStepButton.tsx
> +// const styles = StyleSheet.create({
- [x] removed commented code

2024-04-04 14:14 UTC, LenaYork commented on packages/app/lib/assets/BackArrowSVG.js
Because the use of the SVG file was done in accordance with the pattern (addGender) in another pull request, agreed upon with Natalia (this library is already installed in her pull request).

2024-04-04 14:21 UTC, LenaYork commented on packages/app/components/ui/PreviousStepButton.tsx
> +      style={[styles.circle, { backgroundColor: isPressed ? '#FB8F67' : '#FEDED2' }]}
The state of the button (its background color) depends on whether the user has pressed it or not. The handlers for these events are defined inside the current component. Should I move the handlers to the parent component along with the background color? In order to move them to the parent component, I also need to move onPressInHandler and onPressOutHandler there, right?

2024-04-04 15:10 UTC, LenaYork commented on packages/app/components/ui/NextStepButton.tsx
> +  styles: {
I'm still confused about this part. Could you please elaborate what you would like me to do?

2024-04-05 02:22 UTC, NataliaDoudkina commented on packages/app/components/profileBuilder/AddName.tsx
> +            caption="next"
keep the lower case since it was discussed

2024-04-05 02:22 UTC, NataliaDoudkina commented on packages/app/components/ui/PreviousStepButton.tsx
> +      style={[styles.circle, { backgroundColor: isPressed ? '#FB8F67' : '#FEDED2' }]}
i think you should keep the handlers here, just make sure they do what they are supposed to -  pass the action to the main handler in the parent component

2024-04-05 13:29 UTC, LenaYork commented on yarn.lock
- [x] rolled back changed in the file

2024-05-21 14:56 UTC, merged